### ISSUE TITLE
Issuer does not become ready

### ISSUE THREAD

**Issue by snackewm** [intel/trusted-certificate-issuer#40]
Using the main branch of TCS and the Trusted Attestation Controller along with KMRA 2.0, the TCS Issuer,
Kubernetes cluster is v1.24.3, the following TCS Issuer does not become ready.

```
apiVersion: tcs.intel.com/v1alpha1
kind: TCSIssuer
metadata:
    name: my-ca
    namespace: sandbox
spec:
    secretName: my-ca-cert
    selfSign: false
```
Does not become Ready, even though it appears that all operations (quote verification, wrapped key transfer, wrapped key secret creation) have occurred.

```
~/git/trusted-attestation-controller/sandbox$ kubectl get quoteattestation,tcsissuer,secret -n sandbox
NAME                                   AGE
quoteattestation.tcs.intel.com/my-ca   24m

NAME                            AGE   READY   REASON      MESSAGE
tcsissuer.tcs.intel.com/my-ca   25m   False   Reconcile   Initiated key provisioning using QuoteAttestation

NAME           TYPE     DATA   AGE
secret/my-ca   Opaque   2      24m
```
Logs attached.
[tac-plugin.log](https://github.com/intel/trusted-certificate-issuer/files/9261339/tac-plugin.log)
[tcs.log](https://github.com/intel/trusted-certificate-issuer/files/9261340/tcs.log)
[kmra.log](https://github.com/intel/trusted-certificate-issuer/files/9261341/kmra.log)
[tac.log](https://github.com/intel/trusted-certificate-issuer/files/9261343/tac.log)
