### ISSUE TITLE
Extend the self-signed issuer to configure key type and certificate details

### ISSUE THREAD

**Issue by avalluri** [intel/trusted-certificate-issuer#6]
Current implementation chooses the RSA key and its own certificate parameters for a self-signed issuer.
Admin should be to choose CA private key type and size, and the certificate parameters like subject, duration, DNS names etc.,

Extend the Issuer spec to accommodate key and certificate parameters and consider them while provisions the self-signed issuer.

Sample self-signed issuer would look like:
```
apiVersion: tcs.intel.com/v1alpha1
kind: TCSIssuer
metadata:
    name: my-ca
    namespace: sandbox
spec:
    secretName: my-ca-cert
    selfSigned:
      privateKey:
        algorithm: RSA // or ECDSA
        size: 3072
      certificate:
        duration: 3650d
        renewBefore: 10d
        commonName: test-name
        dnsNames: [ "www.test-name.com" ]
```
